-- Database: GLOBALPLA Metadata version: 2 Exported: Feb 21, 2022
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6529_Scan_Log" USING 'GCG_6529_Scan_Log.mkd' PAGESIZE=4096 (
 "PARTNUMBER" CHAR(20),
 "STATIONNUMBER" CHAR(20),
 "USER_SCAN" CHAR(8),
 "BOM_LIST" LONGVARCHAR,
 "STATUS_BOM" INTEGER,
 "DATE_BOM" DATE,
 "VERSION_DOC" INTEGER,
 "STATUS_DOC" INTEGER,
 "DATE_DOC" DATE );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
